name: Build and Publish

on:
  push:
    branches:
      - master
      - 'releases/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Increment version
        id: version
        uses: kodexa-ai/Bump-N-Tag-Version@master
        with:
          file_name: './VERSION'
          tag_version: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Export VERSION
        run: |
          echo "::set-env name=CURRENT_VERSION::$(cat ./VERSION)"
        shell: bash
      - name: Install dependencies
        run: |
          conda env create -f environment.yml --force
          export PATH="/usr/share/miniconda/bin:$PATH"
      - name: Build Package and Publish
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate kodexa
          python setup.py test sdist bdist_wheel
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}